name: CICD Pipeline

on:
  push:
    branches:
      - main


jobs:
  Testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run start

